/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import Interfaces.GuessWhoInterface;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author rick
 */
public class GuessWhoView extends javax.swing.JFrame {

    GuessWhoInterface GWInterface;
    GuessWhoClientStatesThread stateThread;
    String answer;
    ArrayList<JLabel> labels;
    /**
     * Creates new form GuessWhoView
     */
    public GuessWhoView() {
        initComponents();
        try{
            GWInterface = new GuessWhoClientTCP("localhost", 2015);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al conectar", "Chat", JOptionPane.ERROR_MESSAGE);
        }
        labels = new ArrayList();
        labels.add(LabelAna);
        labels.add(LabelPatrick);
        labels.add(LabelCraig);
        labels.add(LabelJoe);
        labels.add(LabelRebecca);
        labels.add(LabelTom);
        labels.add(LabelCindy);
        labels.add(LabelHeather);
        labels.add(LabelEric);
        labels.add(LabelStella);
        labels.add(LabelRobert);
        labels.add(LabelSam);
        labels.add(LabelSarah);
        labels.add(LabelGary);
        labels.add(LabelMary);
        labels.add(LabelJack);
        labels.add(LabelTheresa);
        labels.add(LabelLuna);
    }
    
    public void whoIsOnLine(String onlines){
    
    }
    
    public void activeChallenges(String challenges){
    
    }
    
    public void seeTurn(String trurn){
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LabelAna = new javax.swing.JLabel();
        LabelPatrick = new javax.swing.JLabel();
        LabelCraig = new javax.swing.JLabel();
        LabelJoe = new javax.swing.JLabel();
        LabelRebecca = new javax.swing.JLabel();
        LabelTom = new javax.swing.JLabel();
        LabelSam = new javax.swing.JLabel();
        LabelRobert = new javax.swing.JLabel();
        LabelStella = new javax.swing.JLabel();
        LabelEric = new javax.swing.JLabel();
        LabelHeather = new javax.swing.JLabel();
        LabelCindy = new javax.swing.JLabel();
        LabelSarah = new javax.swing.JLabel();
        LabelGary = new javax.swing.JLabel();
        LabelMary = new javax.swing.JLabel();
        LabelJack = new javax.swing.JLabel();
        LabelTheresa = new javax.swing.JLabel();
        LabelLuna = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HairColor = new javax.swing.JComboBox();
        EyesColor = new javax.swing.JComboBox();
        SkinColor = new javax.swing.JComboBox();
        Sex = new javax.swing.JComboBox();
        Glases = new javax.swing.JComboBox();
        Barb = new javax.swing.JComboBox();
        Moustache = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        AskCharacter = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        LabelMyCharacter = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LabelTurn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAcceptChallenge = new javax.swing.JButton();
        btnRejectChallenge = new javax.swing.JButton();
        btnChallenge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        LabelAna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Ana.png"))); // NOI18N
        LabelAna.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Ana2.png"))); // NOI18N

        LabelPatrick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Patrick.png"))); // NOI18N

        LabelCraig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Craig.png"))); // NOI18N
        LabelCraig.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Craig2.png"))); // NOI18N

        LabelJoe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Joe.png"))); // NOI18N
        LabelJoe.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Joe2.png"))); // NOI18N

        LabelRebecca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Rebecca.png"))); // NOI18N
        LabelRebecca.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Rebecca2.png"))); // NOI18N

        LabelTom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Tom.png"))); // NOI18N
        LabelTom.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Tom2.png"))); // NOI18N

        LabelSam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Sam.png"))); // NOI18N
        LabelSam.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Sam2.png"))); // NOI18N

        LabelRobert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Robert.png"))); // NOI18N
        LabelRobert.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Robert2.png"))); // NOI18N

        LabelStella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Stella.png"))); // NOI18N
        LabelStella.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Stella2.png"))); // NOI18N

        LabelEric.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Eric.png"))); // NOI18N
        LabelEric.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Eric2.png"))); // NOI18N

        LabelHeather.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Heater.png"))); // NOI18N
        LabelHeather.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Heater2.png"))); // NOI18N

        LabelCindy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Cindy.png"))); // NOI18N
        LabelCindy.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Cindy2.png"))); // NOI18N

        LabelSarah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Sarah.png"))); // NOI18N
        LabelSarah.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Sarah2.png"))); // NOI18N

        LabelGary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Gary.png"))); // NOI18N
        LabelGary.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Gary2.png"))); // NOI18N

        LabelMary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Mary.png"))); // NOI18N
        LabelMary.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Mary2.png"))); // NOI18N

        LabelJack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Jack.png"))); // NOI18N
        LabelJack.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Jack2.png"))); // NOI18N

        LabelTheresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Theresa.png"))); // NOI18N
        LabelTheresa.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Theresa2.png"))); // NOI18N

        LabelLuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Luna.png"))); // NOI18N
        LabelLuna.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/Luna2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LabelAna, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelPatrick, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelCraig, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelJoe, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelRebecca, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelTom, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LabelCindy, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelHeather, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelEric, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelStella, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelRobert, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelSam, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LabelSarah, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelGary, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelMary, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelJack, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelTheresa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelLuna, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAna, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPatrick, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCraig, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelJoe, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRebecca, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTom, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCindy, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelHeather, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEric, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelStella, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRobert, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSam, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSarah, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelGary, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelMary, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelJack, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTheresa, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLuna, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("My character");

        jLabel3.setText("Preguntas:");

        HairColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amarillo", "Cafe", "Naranja", "Negro", " ", " ", " " }));
        HairColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HairColorActionPerformed(evt);
            }
        });

        EyesColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Azul", "Cafe", "Naranja", "Negro", "Verde" }));

        SkinColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blanco", "Negro" }));

        Sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));

        Glases.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));

        Barb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));

        Moustache.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));

        jLabel4.setText("Color de cabello");

        jLabel5.setText("Color de ojos");

        jLabel6.setText("Color de piel");

        jLabel7.setText("Bigote");

        jLabel8.setText("Barba");

        jLabel9.setText("Gafas");

        jLabel10.setText("Sexo");

        AskCharacter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ana", "Patrick", "Craig", "Joe", "Rebecca", "Tom", "Cindy", "Heather", "Eric", "Stella", "Robert", "Sam", "Sarah", "Gray", "Mary", "Jack", "Theresa", "Luna", " " }));

        jLabel11.setText("Personaje");

        LabelMyCharacter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/resourses/img/User.png"))); // NOI18N

        jLabel13.setText("TURNO:");

        LabelTurn.setText("jLabel13");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelMyCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(HairColor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EyesColor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SkinColor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Moustache, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(Barb, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Glases, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(111, 111, 111)
                                        .addComponent(jLabel10)
                                        .addGap(64, 64, 64)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AskCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel11))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(50, 50, 50)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel6)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel3))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(LabelTurn))
                .addGap(76, 76, 76))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(LabelMyCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(HairColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EyesColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SkinColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Moustache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(AskCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Barb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Glases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(LabelTurn)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel1.setText("RETOS:");

        jLabel12.setText("ON LINE:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        btnAcceptChallenge.setText("Aceptar");

        btnRejectChallenge.setText("Rechazar");

        btnChallenge.setText("Retar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(31, 31, 31)
                                        .addComponent(btnChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAcceptChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(btnRejectChallenge)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRejectChallenge)
                            .addComponent(btnAcceptChallenge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(btnChallenge))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HairColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HairColorActionPerformed
        ArrayList<Characters> characterss = null;
        characterss = pjs.getCharacters();
        if(GWInterface.AskCharacteristic("hairColor "+ HairColor.getItemAt(HairColor.getSelectedIndex()))){
            for (int i = 0; i< characterss.size(); i++) {                
                if (!characterss.get(i).getSelfcharacteristic().get(1).equals(HairColor.getItemAt(HairColor.getSelectedIndex()))) {//si el character tiene la misma característica
                    labels.get(i).setEnabled(false);
                }
            }
        }else{
            for (int i = 0; i< characterss.size(); i++) {                
                if (characterss.get(i).getSelfcharacteristic().get(1).equals(HairColor.getItemAt(HairColor.getSelectedIndex()))) {//si el character tiene la misma característica
                    labels.get(i).setEnabled(false);
                }
            }
        }
    }//GEN-LAST:event_HairColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessWhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessWhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessWhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessWhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessWhoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AskCharacter;
    private javax.swing.JComboBox Barb;
    private javax.swing.JComboBox EyesColor;
    private javax.swing.JComboBox Glases;
    private javax.swing.JComboBox HairColor;
    private javax.swing.JLabel LabelAna;
    private javax.swing.JLabel LabelCindy;
    private javax.swing.JLabel LabelCraig;
    private javax.swing.JLabel LabelEric;
    private javax.swing.JLabel LabelGary;
    private javax.swing.JLabel LabelHeather;
    private javax.swing.JLabel LabelJack;
    private javax.swing.JLabel LabelJoe;
    private javax.swing.JLabel LabelLuna;
    private javax.swing.JLabel LabelMary;
    private javax.swing.JLabel LabelMyCharacter;
    private javax.swing.JLabel LabelPatrick;
    private javax.swing.JLabel LabelRebecca;
    private javax.swing.JLabel LabelRobert;
    private javax.swing.JLabel LabelSam;
    private javax.swing.JLabel LabelSarah;
    private javax.swing.JLabel LabelStella;
    private javax.swing.JLabel LabelTheresa;
    private javax.swing.JLabel LabelTom;
    private javax.swing.JLabel LabelTurn;
    private javax.swing.JComboBox Moustache;
    private javax.swing.JComboBox Sex;
    private javax.swing.JComboBox SkinColor;
    private javax.swing.JButton btnAcceptChallenge;
    private javax.swing.JButton btnChallenge;
    private javax.swing.JButton btnRejectChallenge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
    //jButton1 = new JButton();
    //jLabel1
            
//Icon icon = new ImageIcon(getClass().getResource("bangheadonwall.jpg")); 
//JLabel label = new JLabel("An icon", image);
}
